version: '3.7'

services:
 # api:
 #   image: tech-challenge:latest
 #   container_name: app
 #   build:
 #     context: .
 #     dockerfile: Dockerfile
 #   depends_on:
 #     - db
 #   environment:
 #     - DB_ENDPOINT=db:5432
 #     - DB_NAME=selforder
 #     - DB_USERNAME=selforder
 #     - DB_PASSWORD=self@Order123!
 #     - ADMIN_ACCESS_TOKEN=token
 #     - MOCK_PAYMENT_PROVIDER=true
 #     - MP_TOKEN=token
 #     - MP_USER_ID=userId
 #     - MP_POS_ID=postId
 #     - MP_WEBHOOK_BASE_URL=webhookBaseUrl
 #   ports:
 #     - "8080:8080"
 #   restart: always

  payment_db:
    image: amazon/dynamodb-local:latest
    ports:
      - "54000:8000"
    environment:
      AWS_ACCESS_KEY_ID: "fakekey"
      AWS_SECRET_ACCESS_KEY: "fakeaccesskey"
      AWS_REGION: us-east-2
    command: ["-D\"java.library.path\"=./DynamoDBLocal_lib", "-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]

volumes:
  db:
    driver: local
