version: '3.7'

services:
  payments_api:
    image: fiap-3soat-g15-payments-api:latest
    container_name: payments_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - payments_db
    environment:
      SPRING_PROFILES_ACTIVE: local
      AWS_ACCESS_KEY_ID: "fakekey"
      AWS_SECRET_ACCESS_KEY: "fakeaccesskey"
      AWS_DYNAMODB_ENDPOINT: payments_db:54000
      AWS_REGION: us-east-1
      ADMIN_ACCESS_TOKEN: token
      MOCK_PAYMENT_PROVIDER: true
      MP_TOKEN: token
      MP_USER_ID: userId
      MP_POS_ID: postId
      MP_WEBHOOK_BASE_URL: webhookBaseUrl
      ORDERS_SERVICE_URL: http://localhost:8080
    ports:
      - "8082:8082"
    restart: always

  payments_db:
    image: amazon/dynamodb-local:latest
    container_name: payments_db
    ports:
      - "54000:8000"
    environment:
      AWS_ACCESS_KEY_ID: "fakekey"
      AWS_SECRET_ACCESS_KEY: "fakeaccesskey"
      AWS_REGION: us-east-1
    command: ["-D\"java.library.path\"=./DynamoDBLocal_lib", "-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]

volumes:
  payments_db:
    driver: local
