name: payments-api

services:
  payments_api:
    image: fiap-3soat-g15-payments-api:latest
    container_name: payments_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      payments_db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: local
      AWS_ACCESS_KEY_ID: "fakekey"
      AWS_SECRET_ACCESS_KEY: "fakeaccesskey"
      AWS_DYNAMODB_ENDPOINT: http://paymentsdb:54000
      AWS_REGION: us-east-2
      MOCK_PAYMENT_PROVIDER: true
      MP_TOKEN: token
      MP_USER_ID: userId
      MP_POS_ID: postId
      MP_WEBHOOK_BASE_URL: webhookBaseUrl
      ORDERS_SERVICE_URL: http://localhost:8080
    ports:
      - "8082:8082"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  payments_db:
    image: amazon/dynamodb-local:latest
    container_name: payments_db
    hostname: paymentsdb
    ports:
      - "54000:8000"
    environment:
      AWS_ACCESS_KEY_ID: "fakekey"
      AWS_SECRET_ACCESS_KEY: "fakeaccesskey"
      AWS_REGION: us-east-2
    command: ["-D\"java.library.path\"=./DynamoDBLocal_lib", "-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: localstack-sqs-sns
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=us-east-2
    volumes:
      - ./src/main/resources/localstack/localstack-init.sh:/etc/localstack/init/ready.d/init-aws.sh

volumes:
  payments_db:
