version: '3.7'

services:
  api:
    image: fiap-3soat-g15-payments-api:latest
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      AWS_DYNAMODB_ENDPOINT: payment_db:54000
      AWS_ACCESS_KEY_ID: "fakekey"
      AWS_SECRET_ACCESS_KEY: "fakeaccesskey"
      AWS_REGION: us-east-1
      ADMIN_ACCESS_TOKEN: token
      MOCK_PAYMENT_PROVIDER: true
      MP_TOKEN: token
      MP_USER_ID: userId
      MP_POS_ID: postId
      MP_WEBHOOK_BASE_URL: webhookBaseUrl
    ports:
      - "8080:8080"
    restart: always

  payment_db:
    image: amazon/dynamodb-local:latest
    ports:
      - "54000:8000"
    environment:
      AWS_ACCESS_KEY_ID: "fakekey"
      AWS_SECRET_ACCESS_KEY: "fakeaccesskey"
      AWS_REGION: us-east-1
    command: ["-D\"java.library.path\"=./DynamoDBLocal_lib", "-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]

volumes:
  db:
    driver: local
