local: true

payment-provider:
  mock: true

spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      credentials:
        access-key: localstack
        secret-key: localstack
      region:
        static: ${AWS_REGION}

server:
  port: 8081
